# Generated by Django 6.0 on 2026-04-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
